# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        "/portfolio/:title.html"

# Setup
title:            Marcos Tam
tagline:          'Analyst at Deloitte Digital'
description:      'Analyst at Deloitte Digital'
url:              
baseurl:          /

author:
  name:           'Marcos Tam'
  url:            

paginate:         15
paginate_path:    "/portfolio/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           

# Gems
gems:             [jekyll-paginate]